version: '2'

services:
  db-mueblestgo:
    image: 'mysql'
    restart: always
    environment:
      - MYSQL_DATABASE=mueblestgo
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
    ports:
      - 3306:3306      
  mueblestgo:
    image: 'inse1n/mueblestgo'
    restart: on-failure
    container_name: mueblestgo
    depends_on:
      - db-mueblestgo
    environment:
      - DB_URL=jdbc:mysql://db-mueblestgo:3306/mueblestgo?autorReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      - DB_NAME=mueblestgo
      - DB_USR=root
      - DB_PSW=root
      - DB_DTSRC=com.mysql.cj.jdbc.Driver
    ports:
      - 8080:8080
    volumes:
      -  mueblestgo_data:/var/lib/mysql
volumes:
  mueblestgo_data:             