version: '3.8'
services:
  db-mueblestgo:
    image: 'mysql'
    restart: always
    environment:
      - MYSQL_DATABASE=mueblestgo
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
    ports:
      - 3306:3306      
    volumes:
      - mueblestgo_data:/var/lib/mysql
  mueblestgo:
    image: 'inse1n/mueblestgo'
    restart: on-failure
    container_name: mueblestgo
    depends_on:
      - db-mueblestgo
    environment:
      - DB_HOSTNAME=db-mueblestgo
      - DB_PORT=3306
      - DB_NAME=mueblestgo
      - DB_USR=root
      - DB_PSW=root
    ports:
      - 8080:8080
  nginx:
    container_name: nginx-proxy
    image: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - mueblestgo     
volumes:
  mueblestgo_data: