spring:
  application:
    name: tingeso
  jpa:
    show-sql: true
    hibernate:
      dialect: MySQL8Dialect
      ddl-auto: create
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOSTNAME}:${DB_PORT}/${DB_NAME}?autorReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
    username: ${DB_USR}
    password: ${DB_PSW}